global using UnivercityApiBackend.Configuration.Extensions;
global using Models.Context;
global using Microsoft.EntityFrameworkCore;
global using UnivercityApiBackend.Controllers.Base;
global using Services.ServicesManager;
global using Microsoft.AspNetCore.Mvc;
global using Models.Entities;
global using Repository.IRepositoryGeneric;
global using Repository.RepositoryGeneric;